// Protocol message types for Hues and Cues

export const C2S = {
    CREATE_ROOM: 'CREATE_ROOM',
    JOIN_ROOM: 'JOIN_ROOM',
    REJOIN_ROOM: 'REJOIN_ROOM',
    START_GAME: 'START_GAME',
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
    PICK_TARGET: 'PICK_TARGET',
    SUBMIT_CLUE: 'SUBMIT_CLUE',
    SUBMIT_GUESS: 'SUBMIT_GUESS',
    KICK_PLAYER: 'KICK_PLAYER',
};

export const S2C = {
    ROOM_CREATED: 'ROOM_CREATED',
    ROOM_JOINED: 'ROOM_JOINED',
    PLAYER_JOINED: 'PLAYER_JOINED',
    PLAYER_LEFT: 'PLAYER_LEFT',
    PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
    PLAYER_RECONNECTED: 'PLAYER_RECONNECTED',
    SETTINGS_UPDATED: 'SETTINGS_UPDATED',
    PHASE_CHANGED: 'PHASE_CHANGED',
    GUESS_ACK: 'GUESS_ACK',
    REVEAL: 'REVEAL',
    GAME_OVER: 'GAME_OVER',
    ERROR: 'ERROR',
    TIMER_SYNC: 'TIMER_SYNC',
};

export const PHASES = {
    LOBBY: 'lobby',
    PICK_TARGET: 'pick_target',
    CLUE: 'clue',
    GUESS: 'guess',
    REVEAL: 'reveal',
    GAME_OVER: 'game_over',
};
